# frozen_string_literal: true

# Patch BlackHoleStruct to handle arrays consistently.
#
# The upstream gem does not recurse into arrays — hashes inside arrays
# are not converted to BlackHoleStruct on construction, and are not
# converted back to plain Hash on #to_h.  This causes key-type
# inconsistencies after a Resource round-trip (symbol keys become
# string keys inside arrays).
#
# These two patches fix both directions:
#   initialize — converts hashes inside arrays to BlackHoleStruct
#   to_h       — converts BlackHoleStruct/arrays back to plain objects
class BlackHoleStruct
  def initialize(hash = {})
    raise ArgumentError, "Argument should be a Hash" unless hash.is_a?(Hash)

    @table = {}
    hash.each do |key, value|
      @table[key.to_sym] = deep_wrap(value)
    end
  end

  def to_h
    hash = {}
    @table.each do |key, value|
      hash[key] = deep_unwrap(value)
    end
    hash
  end

  private

  def deep_wrap(value)
    case value
    when Hash  then self.class.new(value)
    when Array then value.map { |v| deep_wrap(v) }
    else       value
    end
  end

  def deep_unwrap(value)
    case value
    when self.class then value.to_h
    when Array      then value.map { |v| deep_unwrap(v) }
    else            value
    end
  end
end

module Kube
  module Cluster
    class Manifest < Kube::Schema::Manifest
      # Base class for manifest middleware.
      #
      # Middleware receives a single resource and returns either:
      #   - A single resource (transform)
      #   - An array of resources (generative — e.g. Deployment in, [Deployment, Service] out)
      #
      # The stack processes the full manifest at each stage, so resources
      # generated by one middleware flow through all subsequent stages.
      #
      # Transform example:
      #
      #   class AddTeamLabel < Middleware
      #     def call(resource)
      #       h = resource.to_h
      #       h[:metadata][:labels][:"app.kubernetes.io/team"] = "platform"
      #       rebuild(resource, h)
      #     end
      #   end
      #
      # Generative example:
      #
      #   class ServiceForDeployment < Middleware
      #     def call(resource)
      #       return resource unless pod_bearing?(resource)
      #       service = build_service_from(resource)
      #       [resource, service]
      #     end
      #   end
      #
      class Middleware
        POD_BEARING_KINDS = %w[Deployment StatefulSet DaemonSet Job CronJob ReplicaSet].freeze

        CLUSTER_SCOPED_KINDS = %w[
          Namespace ClusterRole ClusterRoleBinding
          PersistentVolume StorageClass IngressClass
          CustomResourceDefinition PriorityClass
          RuntimeClass VolumeAttachment
          CSIDriver CSINode
        ].freeze

        def initialize(**opts)
          @opts = opts
        end

        # Override in subclasses. Receives a single Resource, returns
        # a single Resource (transform) or an array of Resources
        # (generative).
        def call(resource)
          resource
        end

        private

          # Build a new resource of the same schema subclass from a hash.
          def rebuild(resource, hash)
            resource.class.new(hash)
          end

          # Read a label value from the resource.
          def label(resource, key)
            labels = resource.to_h.dig(:metadata, :labels) || {}
            labels[key.to_sym] || labels[key.to_s]
          end

          # Read an annotation value from the resource.
          def annotation(resource, key)
            annotations = resource.to_h.dig(:metadata, :annotations) || {}
            annotations[key.to_sym] || annotations[key.to_s]
          end

          # The resource kind as a String (e.g. "Deployment").
          def kind(resource)
            h = resource.to_h
            (h[:kind] || h["kind"]).to_s
          end

          # Is this a resource that contains a pod template?
          def pod_bearing?(resource)
            POD_BEARING_KINDS.include?(kind(resource))
          end

          # Is this a cluster-scoped resource (no namespace)?
          def cluster_scoped?(resource)
            CLUSTER_SCOPED_KINDS.include?(kind(resource))
          end

          # Returns the pod template spec path from a resource hash,
          # accounting for CronJob's extra nesting.
          def pod_template(hash)
            if kind_from_hash(hash) == "CronJob"
              hash.dig(:spec, :jobTemplate, :spec, :template, :spec)
            else
              hash.dig(:spec, :template, :spec)
            end
          end

          # Walk every container list in a pod spec (containers,
          # initContainers) and yield each container hash.
          def each_container(pod_spec, &block)
            return unless pod_spec

            [:containers, :initContainers].each do |key|
              Array(pod_spec[key]).each(&block)
            end
          end

          # Extract kind from a hash (symbol or string keys).
          def kind_from_hash(hash)
            (hash[:kind] || hash["kind"]).to_s
          end

          # Deep-merge two hashes (right wins on conflict).
          def deep_merge(base, overlay)
            base.merge(overlay) do |_key, old_val, new_val|
              if old_val.is_a?(Hash) && new_val.is_a?(Hash)
                deep_merge(old_val, new_val)
              else
                new_val
              end
            end
          end
      end
    end
  end
end
