services:
  cluster:
    image: "rancher/k3s:latest"
    command: server
    privileged: true
    restart: always
    environment:
      - K3S_TOKEN=change-me-or-face-the-consequences
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - .:/output
    ports:
      - 6443:6443
